namespace Astrion.Network
{
    public enum PacketType : byte
    {
        // Client -> Server
        Login = 0x01,
        Move = 0x02,
        Chat = 0x03,
        Attack = 0x04,
        CharacterList = 0x05,
        CharacterCreate = 0x06,
        CharacterDelete = 0x07,
        StateRequest = 0x09,
        StateSave = 0x0A,
        ZoneEnter = 0x0B,
        MonsterHit = 0x0C,
        SkillCast = 0x0D,
        DropClaim = 0x0E,
        StatusUpdate = 0x0F,
        ClientLog = 0x10,
        FriendAdd = 0x11,
        FriendRemove = 0x12,
        FriendListRequest = 0x13,
        FriendAccept = 0x14,
        FriendReject = 0x15,
        FriendCancel = 0x16,
        Whisper = 0x17,
        PartyInvite = 0x18,
        PartyAccept = 0x19,
        PartyReject = 0x1A,
        PartyLeave = 0x1B,
        PartyKick = 0x1C,
        PartyRequest = 0x1D,
        RankingRequest = 0x1E,
        TradeRequest = 0x1F,
        TradeAccept = 0x20,
        TradeReject = 0x21,
        TradeOffer = 0x22,
        TradeGold = 0x23,
        TradeLock = 0x24,
        TradeUnlock = 0x25,
        TradeConfirm = 0x26,
        TradeCancel = 0x27,
        BlockAdd = 0x28,
        BlockRemove = 0x29,
        BlockListRequest = 0x2A,
        AchievementListRequest = 0x2B,
        AuctionListRequest = 0x2C,
        AuctionRegister = 0x2D,
        AuctionBuy = 0x2E,
        AuctionCancel = 0x2F,

        // Server -> Client
        LoginResult = 0x81,
        SpawnPlayer = 0x82,
        DespawnPlayer = 0x83,
        PlayerMoved = 0x84,
        ChatMessage = 0x85,
        WorldState = 0x86,
        CharacterListResult = 0x87,
        CharacterCreateResult = 0x88,
        CharacterDeleteResult = 0x89,
        StateData = 0x8A,
        MonsterSpawn = 0x90,
        MonsterMove = 0x91,
        MonsterDie = 0x92,
        MonsterHp = 0x93,
        SkillBroadcast = 0x94,
        ExpGained = 0x95,
        DropSpawn = 0x96,
        DropGranted = 0x97,
        DropRemoved = 0x98,
        PlayerStatus = 0x99,
        StateAck = 0x9A,
        MonsterAttack = 0x9B,
        FriendListData = 0xA0,
        FriendError = 0xA1,
        FriendAddedBy = 0xA2,
        FriendRequestFrom = 0xA3,
        WhisperResult = 0xA4,
        PartyUpdate = 0xA5,
        PartyInviteFrom = 0xA6,
        PartyError = 0xA7,
        RankingData = 0xA8,
        TradeRequestFrom = 0xA9,
        TradeOpen = 0xAA,
        TradeState = 0xAB,
        TradeResult = 0xAC,
        TradeError = 0xAD,
        BlockListData = 0xAE,
        AchievementUnlock = 0xAF,
        AchievementListData = 0xB0,
        AuctionListData = 0xB1,
        AuctionResult = 0xB2,
        SessionKicked = 0xB3,
    }
}
